CREATE TABLE `trialbigdata` (
    `name` VARCHAR(50) NULL DEFAULT NULL,
    `phone` VARCHAR(50) NULL DEFAULT NULL,
    `email` VARCHAR(50) NULL DEFAULT NULL,
    `address` VARCHAR(100) NULL DEFAULT NULL,
    `company` VARCHAR(50) NULL DEFAULT NULL,
    `position` VARCHAR(50) NULL DEFAULT NULL,
    `hobby` VARCHAR(50) NULL DEFAULT NULL,
    `card` VARCHAR(50) NULL DEFAULT NULL,
    `birthdate` VARCHAR(50) NULL DEFAULT NULL,
    `site` VARCHAR(50) NULL DEFAULT NULL,
    `sex` VARCHAR(10) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;